//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.DTO.Responses;
using StreamChat.Core.DTO.Events;
using StreamChat.Core.DTO.Models;

namespace StreamChat.Core.DTO.Requests
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0))")]
    public enum ConfigRequestDefaultRole
    {

        [System.Runtime.Serialization.EnumMember(Value = @"attendee")]
        Attendee = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"publisher")]
        Publisher = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"subscriber")]
        Subscriber = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"admin")]
        Admin = 3,

    }

}

