//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Requests
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct CreateBlockListRequestTypeInternalDTO : System.IEquatable<CreateBlockListRequestTypeInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<CreateBlockListRequestTypeInternalDTO>
    {
        public string Value { get; }

        public static readonly CreateBlockListRequestTypeInternalDTO Regex = new CreateBlockListRequestTypeInternalDTO("regex");
        public static readonly CreateBlockListRequestTypeInternalDTO Domain = new CreateBlockListRequestTypeInternalDTO("domain");
        public static readonly CreateBlockListRequestTypeInternalDTO Email = new CreateBlockListRequestTypeInternalDTO("email");
        public static readonly CreateBlockListRequestTypeInternalDTO Word = new CreateBlockListRequestTypeInternalDTO("word");

        public CreateBlockListRequestTypeInternalDTO(string value)
        {
            Value = value;
        }

        public CreateBlockListRequestTypeInternalDTO Parse(string value) => new CreateBlockListRequestTypeInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(CreateBlockListRequestTypeInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is CreateBlockListRequestTypeInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(CreateBlockListRequestTypeInternalDTO left, CreateBlockListRequestTypeInternalDTO right) => left.Equals(right);

        public static bool operator !=(CreateBlockListRequestTypeInternalDTO left, CreateBlockListRequestTypeInternalDTO right) => !left.Equals(right);

        public static implicit operator CreateBlockListRequestTypeInternalDTO(string value) => new CreateBlockListRequestTypeInternalDTO(value);

        public static implicit operator string(CreateBlockListRequestTypeInternalDTO type) => type.Value;
    }
}
