//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Requests
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0))")]
    public enum TranslateMessageRequestLanguage
    {

        [System.Runtime.Serialization.EnumMember(Value = @"af")]
        Af = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"sq")]
        Sq = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"am")]
        Am = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"ar")]
        Ar = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"az")]
        Az = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"bn")]
        Bn = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"bs")]
        Bs = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"bg")]
        Bg = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"zh")]
        Zh = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"zh-TW")]
        ZhTW = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"hr")]
        Hr = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"cs")]
        Cs = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"da")]
        Da = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"fa-AF")]
        FaAF = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"nl")]
        Nl = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"en")]
        En = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"et")]
        Et = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"fi")]
        Fi = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"fr")]
        Fr = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"fr-CA")]
        FrCA = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"ka")]
        Ka = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"de")]
        De = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"el")]
        El = 22,

        [System.Runtime.Serialization.EnumMember(Value = @"ha")]
        Ha = 23,

        [System.Runtime.Serialization.EnumMember(Value = @"he")]
        He = 24,

        [System.Runtime.Serialization.EnumMember(Value = @"hi")]
        Hi = 25,

        [System.Runtime.Serialization.EnumMember(Value = @"hu")]
        Hu = 26,

        [System.Runtime.Serialization.EnumMember(Value = @"id")]
        Id = 27,

        [System.Runtime.Serialization.EnumMember(Value = @"it")]
        It = 28,

        [System.Runtime.Serialization.EnumMember(Value = @"ja")]
        Ja = 29,

        [System.Runtime.Serialization.EnumMember(Value = @"ko")]
        Ko = 30,

        [System.Runtime.Serialization.EnumMember(Value = @"lv")]
        Lv = 31,

        [System.Runtime.Serialization.EnumMember(Value = @"ms")]
        Ms = 32,

        [System.Runtime.Serialization.EnumMember(Value = @"no")]
        No = 33,

        [System.Runtime.Serialization.EnumMember(Value = @"fa")]
        Fa = 34,

        [System.Runtime.Serialization.EnumMember(Value = @"ps")]
        Ps = 35,

        [System.Runtime.Serialization.EnumMember(Value = @"pl")]
        Pl = 36,

        [System.Runtime.Serialization.EnumMember(Value = @"pt")]
        Pt = 37,

        [System.Runtime.Serialization.EnumMember(Value = @"ro")]
        Ro = 38,

        [System.Runtime.Serialization.EnumMember(Value = @"ru")]
        Ru = 39,

        [System.Runtime.Serialization.EnumMember(Value = @"sr")]
        Sr = 40,

        [System.Runtime.Serialization.EnumMember(Value = @"sk")]
        Sk = 41,

        [System.Runtime.Serialization.EnumMember(Value = @"sl")]
        Sl = 42,

        [System.Runtime.Serialization.EnumMember(Value = @"so")]
        So = 43,

        [System.Runtime.Serialization.EnumMember(Value = @"es")]
        Es = 44,

        [System.Runtime.Serialization.EnumMember(Value = @"es-MX")]
        EsMX = 45,

        [System.Runtime.Serialization.EnumMember(Value = @"sw")]
        Sw = 46,

        [System.Runtime.Serialization.EnumMember(Value = @"sv")]
        Sv = 47,

        [System.Runtime.Serialization.EnumMember(Value = @"tl")]
        Tl = 48,

        [System.Runtime.Serialization.EnumMember(Value = @"ta")]
        Ta = 49,

        [System.Runtime.Serialization.EnumMember(Value = @"th")]
        Th = 50,

        [System.Runtime.Serialization.EnumMember(Value = @"tr")]
        Tr = 51,

        [System.Runtime.Serialization.EnumMember(Value = @"uk")]
        Uk = 52,

        [System.Runtime.Serialization.EnumMember(Value = @"ur")]
        Ur = 53,

        [System.Runtime.Serialization.EnumMember(Value = @"vi")]
        Vi = 54,

    }

}

