//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct AutomodTypeInternalDTO : System.IEquatable<AutomodTypeInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<AutomodTypeInternalDTO>
    {
        public string Value { get; }

        public static readonly AutomodTypeInternalDTO Disabled = new AutomodTypeInternalDTO("disabled");
        public static readonly AutomodTypeInternalDTO Simple = new AutomodTypeInternalDTO("simple");
        public static readonly AutomodTypeInternalDTO AI = new AutomodTypeInternalDTO("AI");

        public AutomodTypeInternalDTO(string value)
        {
            Value = value;
        }

        public AutomodTypeInternalDTO Parse(string value) => new AutomodTypeInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(AutomodTypeInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is AutomodTypeInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(AutomodTypeInternalDTO left, AutomodTypeInternalDTO right) => left.Equals(right);

        public static bool operator !=(AutomodTypeInternalDTO left, AutomodTypeInternalDTO right) => !left.Equals(right);

        public static implicit operator AutomodTypeInternalDTO(string value) => new AutomodTypeInternalDTO(value);

        public static implicit operator string(AutomodTypeInternalDTO type) => type.Value;
    }
}
