//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct BlockListOptionsBehaviorInternalDTO : System.IEquatable<BlockListOptionsBehaviorInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<BlockListOptionsBehaviorInternalDTO>
    {
        public string Value { get; }

        public static readonly BlockListOptionsBehaviorInternalDTO Flag = new BlockListOptionsBehaviorInternalDTO("flag");
        public static readonly BlockListOptionsBehaviorInternalDTO Block = new BlockListOptionsBehaviorInternalDTO("block");
        public static readonly BlockListOptionsBehaviorInternalDTO ShadowBlock = new BlockListOptionsBehaviorInternalDTO("shadow_block");

        public BlockListOptionsBehaviorInternalDTO(string value)
        {
            Value = value;
        }

        public BlockListOptionsBehaviorInternalDTO Parse(string value) => new BlockListOptionsBehaviorInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(BlockListOptionsBehaviorInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is BlockListOptionsBehaviorInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(BlockListOptionsBehaviorInternalDTO left, BlockListOptionsBehaviorInternalDTO right) => left.Equals(right);

        public static bool operator !=(BlockListOptionsBehaviorInternalDTO left, BlockListOptionsBehaviorInternalDTO right) => !left.Equals(right);

        public static implicit operator BlockListOptionsBehaviorInternalDTO(string value) => new BlockListOptionsBehaviorInternalDTO(value);

        public static implicit operator string(BlockListOptionsBehaviorInternalDTO type) => type.Value;
    }
}
