//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// All possibility of string to use
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct ChannelOwnCapabilityInternalDTO : System.IEquatable<ChannelOwnCapabilityInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<ChannelOwnCapabilityInternalDTO>
    {
        public string Value { get; }

        public static readonly ChannelOwnCapabilityInternalDTO BanChannelMembers = new ChannelOwnCapabilityInternalDTO("ban-channel-members");
        public static readonly ChannelOwnCapabilityInternalDTO CastPollVote = new ChannelOwnCapabilityInternalDTO("cast-poll-vote");
        public static readonly ChannelOwnCapabilityInternalDTO ConnectEvents = new ChannelOwnCapabilityInternalDTO("connect-events");
        public static readonly ChannelOwnCapabilityInternalDTO CreateAttachment = new ChannelOwnCapabilityInternalDTO("create-attachment");
        public static readonly ChannelOwnCapabilityInternalDTO DeleteAnyMessage = new ChannelOwnCapabilityInternalDTO("delete-any-message");
        public static readonly ChannelOwnCapabilityInternalDTO DeleteChannel = new ChannelOwnCapabilityInternalDTO("delete-channel");
        public static readonly ChannelOwnCapabilityInternalDTO DeleteOwnMessage = new ChannelOwnCapabilityInternalDTO("delete-own-message");
        public static readonly ChannelOwnCapabilityInternalDTO FlagMessage = new ChannelOwnCapabilityInternalDTO("flag-message");
        public static readonly ChannelOwnCapabilityInternalDTO FreezeChannel = new ChannelOwnCapabilityInternalDTO("freeze-channel");
        public static readonly ChannelOwnCapabilityInternalDTO JoinChannel = new ChannelOwnCapabilityInternalDTO("join-channel");
        public static readonly ChannelOwnCapabilityInternalDTO LeaveChannel = new ChannelOwnCapabilityInternalDTO("leave-channel");
        public static readonly ChannelOwnCapabilityInternalDTO MuteChannel = new ChannelOwnCapabilityInternalDTO("mute-channel");
        public static readonly ChannelOwnCapabilityInternalDTO PinMessage = new ChannelOwnCapabilityInternalDTO("pin-message");
        public static readonly ChannelOwnCapabilityInternalDTO QueryPollVotes = new ChannelOwnCapabilityInternalDTO("query-poll-votes");
        public static readonly ChannelOwnCapabilityInternalDTO QuoteMessage = new ChannelOwnCapabilityInternalDTO("quote-message");
        public static readonly ChannelOwnCapabilityInternalDTO ReadEvents = new ChannelOwnCapabilityInternalDTO("read-events");
        public static readonly ChannelOwnCapabilityInternalDTO SearchMessages = new ChannelOwnCapabilityInternalDTO("search-messages");
        public static readonly ChannelOwnCapabilityInternalDTO SendCustomEvents = new ChannelOwnCapabilityInternalDTO("send-custom-events");
        public static readonly ChannelOwnCapabilityInternalDTO SendLinks = new ChannelOwnCapabilityInternalDTO("send-links");
        public static readonly ChannelOwnCapabilityInternalDTO SendMessage = new ChannelOwnCapabilityInternalDTO("send-message");
        public static readonly ChannelOwnCapabilityInternalDTO SendPoll = new ChannelOwnCapabilityInternalDTO("send-poll");
        public static readonly ChannelOwnCapabilityInternalDTO SendReaction = new ChannelOwnCapabilityInternalDTO("send-reaction");
        public static readonly ChannelOwnCapabilityInternalDTO SendReply = new ChannelOwnCapabilityInternalDTO("send-reply");
        public static readonly ChannelOwnCapabilityInternalDTO SendRestrictedVisibilityMessage = new ChannelOwnCapabilityInternalDTO("send-restricted-visibility-message");
        public static readonly ChannelOwnCapabilityInternalDTO SendTypingEvents = new ChannelOwnCapabilityInternalDTO("send-typing-events");
        public static readonly ChannelOwnCapabilityInternalDTO SetChannelCooldown = new ChannelOwnCapabilityInternalDTO("set-channel-cooldown");
        public static readonly ChannelOwnCapabilityInternalDTO SkipSlowMode = new ChannelOwnCapabilityInternalDTO("skip-slow-mode");
        public static readonly ChannelOwnCapabilityInternalDTO SlowMode = new ChannelOwnCapabilityInternalDTO("slow-mode");
        public static readonly ChannelOwnCapabilityInternalDTO TypingEvents = new ChannelOwnCapabilityInternalDTO("typing-events");
        public static readonly ChannelOwnCapabilityInternalDTO UpdateAnyMessage = new ChannelOwnCapabilityInternalDTO("update-any-message");
        public static readonly ChannelOwnCapabilityInternalDTO UpdateChannel = new ChannelOwnCapabilityInternalDTO("update-channel");
        public static readonly ChannelOwnCapabilityInternalDTO UpdateChannelMembers = new ChannelOwnCapabilityInternalDTO("update-channel-members");
        public static readonly ChannelOwnCapabilityInternalDTO UpdateOwnMessage = new ChannelOwnCapabilityInternalDTO("update-own-message");
        public static readonly ChannelOwnCapabilityInternalDTO UpdateThread = new ChannelOwnCapabilityInternalDTO("update-thread");
        public static readonly ChannelOwnCapabilityInternalDTO UploadFile = new ChannelOwnCapabilityInternalDTO("upload-file");

        public ChannelOwnCapabilityInternalDTO(string value)
        {
            Value = value;
        }

        public ChannelOwnCapabilityInternalDTO Parse(string value) => new ChannelOwnCapabilityInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(ChannelOwnCapabilityInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is ChannelOwnCapabilityInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(ChannelOwnCapabilityInternalDTO left, ChannelOwnCapabilityInternalDTO right) => left.Equals(right);

        public static bool operator !=(ChannelOwnCapabilityInternalDTO left, ChannelOwnCapabilityInternalDTO right) => !left.Equals(right);

        public static implicit operator ChannelOwnCapabilityInternalDTO(string value) => new ChannelOwnCapabilityInternalDTO(value);

        public static implicit operator string(ChannelOwnCapabilityInternalDTO type) => type.Value;
    }
}
