//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct ImageCropTypeInternalDTO : System.IEquatable<ImageCropTypeInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<ImageCropTypeInternalDTO>
    {
        public string Value { get; }

        public static readonly ImageCropTypeInternalDTO Top = new ImageCropTypeInternalDTO("top");
        public static readonly ImageCropTypeInternalDTO Bottom = new ImageCropTypeInternalDTO("bottom");
        public static readonly ImageCropTypeInternalDTO Left = new ImageCropTypeInternalDTO("left");
        public static readonly ImageCropTypeInternalDTO Right = new ImageCropTypeInternalDTO("right");
        public static readonly ImageCropTypeInternalDTO Center = new ImageCropTypeInternalDTO("center");

        public ImageCropTypeInternalDTO(string value)
        {
            Value = value;
        }

        public ImageCropTypeInternalDTO Parse(string value) => new ImageCropTypeInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(ImageCropTypeInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is ImageCropTypeInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(ImageCropTypeInternalDTO left, ImageCropTypeInternalDTO right) => left.Equals(right);

        public static bool operator !=(ImageCropTypeInternalDTO left, ImageCropTypeInternalDTO right) => !left.Equals(right);

        public static implicit operator ImageCropTypeInternalDTO(string value) => new ImageCropTypeInternalDTO(value);

        public static implicit operator string(ImageCropTypeInternalDTO type) => type.Value;
    }
}
