//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct PushPreferenceInputChatLevelInternalDTO : System.IEquatable<PushPreferenceInputChatLevelInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<PushPreferenceInputChatLevelInternalDTO>
    {
        public string Value { get; }

        public static readonly PushPreferenceInputChatLevelInternalDTO All = new PushPreferenceInputChatLevelInternalDTO("all");
        public static readonly PushPreferenceInputChatLevelInternalDTO Mentions = new PushPreferenceInputChatLevelInternalDTO("mentions");
        public static readonly PushPreferenceInputChatLevelInternalDTO None = new PushPreferenceInputChatLevelInternalDTO("none");
        public static readonly PushPreferenceInputChatLevelInternalDTO Default = new PushPreferenceInputChatLevelInternalDTO("default");

        public PushPreferenceInputChatLevelInternalDTO(string value)
        {
            Value = value;
        }

        public PushPreferenceInputChatLevelInternalDTO Parse(string value) => new PushPreferenceInputChatLevelInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(PushPreferenceInputChatLevelInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is PushPreferenceInputChatLevelInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(PushPreferenceInputChatLevelInternalDTO left, PushPreferenceInputChatLevelInternalDTO right) => left.Equals(right);

        public static bool operator !=(PushPreferenceInputChatLevelInternalDTO left, PushPreferenceInputChatLevelInternalDTO right) => !left.Equals(right);

        public static implicit operator PushPreferenceInputChatLevelInternalDTO(string value) => new PushPreferenceInputChatLevelInternalDTO(value);

        public static implicit operator string(PushPreferenceInputChatLevelInternalDTO type) => type.Value;
    }
}
