//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using GetStreamIO.Core.DTO.Responses;
using GetStreamIO.Core.DTO.Requests;
using GetStreamIO.Core.DTO.Events;

namespace GetStreamIO.Core.DTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.5.0 (NJsonSchema v10.6.6.0 (Newtonsoft.Json v9.0.0.0))")]
    public enum AutomodType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"disabled")]
        Disabled = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"simple")]
        Simple = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"AI")]
        AI = 2,

    }

}

