name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Generate manual license file
    runs-on: macos-latest
    steps:
      - name: Download & Install Unity
        shell: bash
        run: |
          curl -L -o ~/Unity.pkg https://download.unity3d.com/download_unity/1fb1bf06830e/MacEditorInstaller/Unity.pkg
          sudo installer -package ~/Unity.pkg -target /
      - name: Generate license file
        shell: bash
        run: sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode  -nographics -createManualActivationFile -quit
        continue-on-error: true
      - name: List dir
        shell: bash
        run: ls ~
        continue-on-error: true
      - name: Pwd
        shell: bash
        run: pwd
        continue-on-error: true
      - name: List current
        shell: bash
        run: ls
        continue-on-error: true
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unity_v2020.3.30f1.alf
          path: Unity_v2020.3.30f1.alf
