name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Generate manual license file
    runs-on: macos-latest
    steps:
      - name: Download Unity & Generate license file
        shell: bash
        run: |
          curl -L -o ~/Unity.pkg https://download.unity3d.com/download_unity/1fb1bf06830e/MacEditorInstaller/Unity.pkg
          sudo installer -package ~/Unity.pkg -target /

          sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode  -nographics -createManualActivationFile

          ls ~
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unity_v2020.3.0f1.alf
          path: ~/Unity_v2020.3.0f1.alf
