name: Run Unity tests on Mac OS

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  testRunner:
    needs: checkLicense
    name: Execute editor tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Unity
        shell: bash
        run: curl -OL  https://download.unity3d.com/download_unity/2ab9c4179772/MacEditorInstaller/Unity.pkg
        
      - name: Install Unity
        shell: bash
        run: sudo installer -package Unity.pkg -target /
        
      - name: ls /Applications/Unity/Unity.app/Contents/MacOS/
        shell: bash
        run: ls /Applications/Unity/Unity.app/Contents/MacOS/
        continue-on-error: true
        
      - name: ls /Applications/
        shell: bash
        run: ls /Applications/
        continue-on-error: true

      - name: MKDIR
        shell: bash
        run: mkdir test_results
        
      - name: Save license
        shell: bash
        run: echo "${{ secrets.UNITY_LICENSE }}" > ~/license.ulf
        
      - name: Print license
        shell: bash
        run: cat ~/license.ulf
        
      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-version: 2021.2.1f1
          unity-username: ${{ secrets.UNITY_ACCOUNT_USER }}
          unity-password: ${{ secrets.UNITY_ACCOUNT_PASS }}
        
      - name: Test open
        shell: bash
        run: sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath $GITHUB_WORKSPACE -username "${{ secrets.UNITY_ACCOUNT_USER }}" -password "${{ secrets.UNITY_ACCOUNT_PASS }}" -quit
        continue-on-error: true
        
      - name: LS Logs dir
        shell: bash
        run: ls ~/Library/Logs/
        continue-on-error: true
        
      - name: LS Unity Logs dir
        shell: bash
        run: ls ~/Library/Logs/Unity/
        continue-on-error: true
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Unity.Entitlements.Audit.log
        continue-on-error: true
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Unity.Licensing.Client.log
        continue-on-error: true
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        continue-on-error: true

      - name: Activate Unity License
        shell: bash
        run: sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -manualLicenseFile "~/license.ulf" -username "${{ secrets.UNITY_ACCOUNT_USER }}" -password "${{ secrets.UNITY_ACCOUNT_PASS }}" -quit
        continue-on-error: true
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        continue-on-error: true
        
      - name: Print user
        shell: bash
        run: echo ${{ secrets.UNITY_ACCOUNT_USER }}
        continue-on-error: true
        
      - name: Activate Unity License 2
        shell: bash
        run: sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -username "${{ secrets.UNITY_ACCOUNT_USER }}" -password "${{ secrets.UNITY_ACCOUNT_PASS }}" -quit
        continue-on-error: true
        
      - name: Print Unity Logs 2
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        continue-on-error: true
        
      - name: Try open project in Unity 
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "$GITHUB_WORKSPACE" -quit
        continue-on-error: true

      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        
      - name: Enable Stream Tests in Unity
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "$GITHUB_WORKSPACE" -executeMethod StreamChat.EditorTools.StreamEditorTools.EnableStreamTestsEnabledCompilerFlag -username "${{ secrets.UNITY_ACCOUNT_USER }}" -password "${{ secrets.UNITY_ACCOUNT_PASS }}" -quit
        
      - name: Run Unity Tests
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "$GITHUB_WORKSPACE" -runTests -testResults test_results/results.xml -username "${{ secrets.UNITY_ACCOUNT_USER }}" -password "${{ secrets.UNITY_ACCOUNT_PASS }}" -quit
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        
      - name: Print Test Results
        shell: bash
        run: cat test_results/results.xml
