name: Run Unity tests on Mac OS

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for the Unity license ☑️
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license ☠️
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  testRunner:
    needs: checkLicense
    name: Execute editor tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Unity
        shell: bash
        run: curl -OL  https://download.unity3d.com/download_unity/cb45f9cae8b7/MacEditorInstaller/Unity.pkg
        
      - name: Install Unity
        shell: bash
        run: sudo installer -package Unity.pkg -target /

      - name: MKDIR
        shell: bash
        run: mkdir test_results
        
      - name: Save license
        shell: bash
        run: echo "${{ env.UNITY_LICENSE }}" > ~/license.ulf
        
      - name: Print license
        shell: bash
        run: cat ~/license.ulf

      - name: Activate Unity License
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -manualLicenseFile ~/license.ulf -logFile -quit
        continue-on-error: true
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        
      - name: Try open project in Unity 
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "$GITHUB_WORKSPACE" -logFile -quit
        continue-on-error: true

      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        
      - name: Enable Stream Tests in Unity
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath $GITHUB_WORKSPACE -executeMethod StreamChat.EditorTools.StreamEditorTools.EnableStreamTestsEnabledCompilerFlag -quit
        
      - name: Run Unity Tests
        shell: bash
        run: /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -projectPath $GITHUB_WORKSPACE -runTests -testResults test_results/results.xml -quit
        
      - name: Print Unity Logs
        shell: bash
        run: cat ~/Library/Logs/Unity/Editor.log
        
      - name: Print Test Results
        shell: bash
        run: cat test_results/results.xml
