name: Test Verify Code

on: workflow_dispatch

jobs:
  testVerifyCodeJob:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: Install node package, `unity-verify-code`
        run: npm install --global https://github.com/GetStream/unity-verify-code
      - name: Run Verify Code
        shell: bash
        run: |
          sudo touch "./code.txt"
          sudo unity-verify-code "${{ secrets.UNITY_ACCOUNT_USER }}" "${{ secrets.EMAIL_PASS }}" "./code.txt"
          
