//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal readonly struct MessageWithChannelResponseTypeInternalDTO : System.IEquatable<MessageWithChannelResponseTypeInternalDTO>, StreamChat.Core.LowLevelClient.IEnumeratedStruct<MessageWithChannelResponseTypeInternalDTO>
    {
        public string Value { get; }

        public static readonly MessageWithChannelResponseTypeInternalDTO Regular = new MessageWithChannelResponseTypeInternalDTO("regular");
        public static readonly MessageWithChannelResponseTypeInternalDTO Ephemeral = new MessageWithChannelResponseTypeInternalDTO("ephemeral");
        public static readonly MessageWithChannelResponseTypeInternalDTO Error = new MessageWithChannelResponseTypeInternalDTO("error");
        public static readonly MessageWithChannelResponseTypeInternalDTO Reply = new MessageWithChannelResponseTypeInternalDTO("reply");
        public static readonly MessageWithChannelResponseTypeInternalDTO System = new MessageWithChannelResponseTypeInternalDTO("system");
        public static readonly MessageWithChannelResponseTypeInternalDTO Deleted = new MessageWithChannelResponseTypeInternalDTO("deleted");

        public MessageWithChannelResponseTypeInternalDTO(string value)
        {
            Value = value;
        }

        public MessageWithChannelResponseTypeInternalDTO Parse(string value) => new MessageWithChannelResponseTypeInternalDTO(value);

        public override string ToString() => Value;

        public bool Equals(MessageWithChannelResponseTypeInternalDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is MessageWithChannelResponseTypeInternalDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(MessageWithChannelResponseTypeInternalDTO left, MessageWithChannelResponseTypeInternalDTO right) => left.Equals(right);

        public static bool operator !=(MessageWithChannelResponseTypeInternalDTO left, MessageWithChannelResponseTypeInternalDTO right) => !left.Equals(right);

        public static implicit operator MessageWithChannelResponseTypeInternalDTO(string value) => new MessageWithChannelResponseTypeInternalDTO(value);

        public static implicit operator string(MessageWithChannelResponseTypeInternalDTO type) => type.Value;
    }
}
